language: node_js
node_js:
  - "4.1"
env:
  - CXX=g++-4.8
install:
  - npm install
  - cd app && npm install && bower install
script:
  - node package.js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
