language: node_js
node_js:
  - "4.1"
env:
  - CXX=g++-4.8
before_install:
  - npm install -g bower
install:
  - apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils
  - npm install
  - cd app
  - npm install
  - bower install
  - cd ../
script:
  - npm run dist
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
